- name: Create admin users
  user:
    name: "admin"
    shell: /bin/bash
    group: sudo
    create_home: yes
    password: "{{ 'admin@123' | password_hash('sha512') }}"
  

- name: Create normal users
  user:
    name: "user-1"
    shell: /bin/bash
    create_home: yes
    password: "{{ 'user@123' | password_hash('sha512') }}"
  